# yolo path
yolo:
  "320":
    config: "./yolo3/v3-320/yolov3.cfg"
    weights: "./yolo3/v3-320/yolov3.weights"
  "416":
    config: "./yolo3/v3-416/yolov3.cfg"
    weights: "./yolo3/v3-416/yolov3.weights"
  "608":
    config: "./yolo3/v3-608/yolov3.cfg"
    weights: "./yolo3/v3-608/yolov3.weights"
  "tiny":
    config: "./yolo3/v3-tiny/yolov3-tiny.cfg"
    weights: "./yolo3/v3-tiny/yolov3-tiny.weights"
  "spp":
    config: "./yolo3/v3-spp/yolov3-spp.cfg"
    weights: "./yolo3/v3-spp/yolov3-spp.weights"

# mahimahi trace path
traces:
  fcc: "./dataset/fcc/traces/"
  belgium: "./dataset/belgium/traces"
  norway: "./dataset/norway/traces"
